name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.FOLDER}}
            sudo git pull

            ENV_FILE_CONTENT="${{ secrets.ENV_FILE }}"
            sudo rm -f .env
            echo "$ENV_FILE_CONTENT" > .env
            
            sudo yarn
            sudo yarn generate

            sudo systemctl restart domutala.service
